Added checks for paths and .profile

diff --git a/bash/add-directory-to-path b/bash/add-directory-to-path
--- a/bash/add-directory-to-path
+++ b/bash/add-directory-to-path
@@ -5,14 +5,42 @@
 # This script checks if a provided directory is already part of the $PATH environment variable
 # and adds it in .profile if not.
 
-# Check arguments - There should be one: The directory path
-if [ "$#" -ne 1 ]; then
+# Read arguments - There should be one: The directory path
+if [ "$#" -eq 1 ]; then
+    DIR=$1
+else
     echo "Usage: $0 <directory path>"
     exit 1
 fi
 
-DIR=$1
-echo "Path: $DIR"
 
-# Check if 
+# Normalize $DIR, if it exists
+if [ -d $DIR ]; then
+    REAL_DIR=`realpath $DIR`
+    echo "Path: $DIR ($REAL_DIR)"
+else
+    echo "Error: Directory '$DIR' does not exist."
+    exit 1
+fi
+
+
+# Check if $DIR is already in $PATH
+FOO=`echo $PATH | sed 's/:/ /g'`
+
+for P in $FOO; do
+    REAL_P=`realpath $P`
+    if [ "$REAL_P" = "$REAL_DIR" ]; then
+        echo "Error: Directory '$REAL_DIR' is already part of PATH variable."
+        exit 1
+    fi
+done
+
+# Check if .profile exitst
+if [ ! -f ~/.profile ]; then
+    echo "Error: File ~/.profile does not exist."
+    exit 1
+fi
+
+
+
 exit 0
